/***************************************************************************
* Project:  OpenCPN
* Purpose:  Open Observer Plugin Control Dialog
* Author:   Jon Gough
*
* Project:  OpenCPN
*
***************************************************************************
*   Copyright (C) 2013 by David S. Register                               *
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
*   This program is distributed in the hope that it will be useful,       *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*   GNU General Public License for more details.                          *
*                                                                         *
*   You should have received a copy of the GNU General Public License     *
*   along with this program; if not, write to the                         *
*   Free Software Foundation, Inc.,                                       *
*   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
**************************************************************************/

#pragma once

/**
 * @file
 * Subclass of ooControlDialogDef, which is generated by wxFormBuilder.
 */

#include <wx/grid.h>

#include "ooControlDialogDef.h"

#include "ooMiniPanel.h"
#include "ooObservations.h"

#include <set>
#include <unordered_map>

///////////////////////////////////////////////////////////////////////////////
/// Class ooControlDialogImpl
///////////////////////////////////////////////////////////////////////////////
class ooControlDialogImpl : public ooControlDialogDef
{
public:
        ooControlDialogImpl(wxWindow *parent);
        ~ooControlDialogImpl();

        void NewProject();
        void UseProject();

        void CreateObservationsTable(ooObservations *observations);
        bool RestoreBackupObservations(int observationsIndex);
        void SetObservationsChoiceCount(int observationsChoiceCount);

        void SetPositionFix(time_t fixTime, double lat, double lon);
        void SetNmeaSentence(const wxString& sentence);
        void SetViewScale(double viewScale);
        void RefreshObservationsGrid();
        void CreateMarkForCompletedObservationIfRequested();
      protected:
        void SetupObservationsForProject();
        bool LoadObservations(const wxString& filename, bool updateFromMarks = true);
        bool SaveObservations(const wxString& filename = wxString(), bool stopObservation = true);
        ooProject GenerateProject() const;
        void SetProjectEditable(bool editable);

        void OnButtonClickProjectEditUse(wxCommandEvent& event);
        void OnButtonClickProjectNew(wxCommandEvent& event);
	      void OnButtonClickProjectNewColumn(wxCommandEvent& event);
        void OnButtonClickProjectDeleteColumn(wxCommandEvent& event);
        void OnProjectColourChanged(wxColourPickerEvent& event);

        void OnButtonClickNewObservation( wxCommandEvent& event );
        void OnButtonClickDeleteObservation( wxCommandEvent& event );
        void OnButtonClickFilterObservations(wxCommandEvent& event);
        void OnButtonClickClearObservationFilter(wxCommandEvent& event);
        void OnButtonClickExportObservations( wxCommandEvent& event );
        void OnButtonClickDataPackage( wxCommandEvent& event ) override;
        void OnButtonClickCreateScientificPackage( wxCommandEvent& event ) override;
        void OnButtonClickUpdateScientificPackage( wxCommandEvent& event ) override;
        void OnButtonClickImportObservations(wxCommandEvent& event);
        void OnCheckBoxShowObservationMarks(wxCommandEvent& event) override;
        void OnButtonClickSaveObservation(wxCommandEvent& event);
        void OnButtonClickLoadObservation(wxCommandEvent& event);
        void ooControlCloseClick(wxCommandEvent& event);
        void ooControlDialogDefOnClose(wxCloseEvent& event);
        void OnButtonClickScanNmea(wxCommandEvent& event);
        void OnButtonClickCleanNmeaRecordings(wxCommandEvent& event) override;
        void OnCheckBoxShowAdvancedNmeaFields(wxCommandEvent& event) override;
        void CommitCurrentObservationsGridEdit();
        void ooControlDialogActivate(wxActivateEvent& event);
        void OnButtonClickOpenResourcesFolder(wxCommandEvent& event);
        void OnButtonClickRefreshListings(wxCommandEvent& event);
        void OnNotebookPageChanged(wxNotebookEvent& event);
        void OnChoiceObservationsChanged(wxCommandEvent& event);
        void OnObservationsGridCellSelect(wxGridEvent& event);
        void OnObservationsGridRangeSelect(wxGridRangeSelectEvent& event);
        void OnProjectGridCellSelect(wxGridEvent& event);
        void OnProjectGridRangeSelect(wxGridRangeSelectEvent& event);
        void OnProjectGridCellChange(wxGridEvent& event);
        void OnObservationsGridCellChange(wxGridEvent& event);

      private:
        void OnBackupTimer(wxTimerEvent& event);
        bool LoadProject(const ooProject& project);
        void OnNmeaFieldUpdate();
        void EnsureProjectHasFieldType(const wxString& field_type,
                                       const wxString& label);
        void ClearCurrentObservationsForNewProject();
        void SetupListingEditors();
        void HideInternalProjectColumns();
        void HideInternalObservationColumns();
        void ApplyObservationTextFilter(const wxString& query);
        void ClearObservationTextFilter();
        wxGridSizesInfo GetUserVisibleObservationColSizes() const;
        bool ObservationMarksArePresent() const;
        void SyncShowObservationMarksCheckboxWithData();
        void RefreshListings();
        void OnProjectGridSelectionChange();

        bool m_markIconsLoaded;
        bool m_showObservationMarks;

        void EnsureMarkIconChoiceContains(const wxString& iconName);
        void SelectMarkIconOrFallback(const wxString& iconName);
        void LoadMarkIconsIfNeeded(const wxString& preferredIconName = wxEmptyString);

        ooMiniPanel *m_MiniPanel;

        wxTimer m_BackupTimer;
        ooProject m_CurrentProject;
        int m_currentObservationsIndex, m_observationsChoiceCount;
        double m_viewScale;

        bool m_isScanningNmea;
        std::unordered_map<wxString, std::set<int>> m_scannedNmeaFields;

        bool m_hasObservationPasteUndo;
        int m_observationPasteUndoRow;
        int m_observationPasteUndoCol;
        wxString m_observationPasteUndoText;

        ooObservations * m_Observations;
        wxGrid* m_ObservationsTable;
        void ApplyModernGridStyle(wxGrid* grid);
        void ApplyProjectGridReadabilityStyle(wxGrid* grid);
        void RefreshGridAppearance(wxGrid* grid);
        void UpdateProjectCellEditors();
        int  GetNmeaFieldCount() const;

        static wxString GetBackupFilename(int index);
};
