/***************************************************************************
* Project:  OpenCPN
* Purpose:  Open Observer Plugin Mini Dialog
* Author:   Alex Mansfield
*
* Project:  OpenCPN
*
***************************************************************************
*   Copyright (C) 2013 by David S. Register                               *
*                                                                         *
*   This program is free software; you can redistribute it and/or modify  *
*   it under the terms of the GNU General Public License as published by  *
*   the Free Software Foundation; either version 2 of the License, or     *
*   (at your option) any later version.                                   *
*                                                                         *
*   This program is distributed in the hope that it will be useful,       *
*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
*   GNU General Public License for more details.                          *
*                                                                         *
*   You should have received a copy of the GNU General Public License     *
*   along with this program; if not, write to the                         *
*   Free Software Foundation, Inc.,                                       *
*   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,  USA.         *
**************************************************************************/

#pragma once

/**
 * @file
 * Subclass of ooMiniDialogDef, which is generated by wxFormBuilder.
 */

#include "ooMiniDialogDef.h"

#include "ooMiniPanel.h"

///////////////////////////////////////////////////////////////////////////////
/// Class ooMiniDialogImpl
///////////////////////////////////////////////////////////////////////////////
class ooMiniDialogImpl : public ooMiniDialogDef
{
        public:
        ooMiniDialogImpl(wxWindow *parent);
        ~ooMiniDialogImpl();

        void SetProjectInfo(const wxString& projectName,
                            const wxColor& projectColor);

        protected:
        void ooMiniDialogDefOnClose(wxCloseEvent& event);

        ooMiniPanel *m_MiniPanel;
};
